# This file is the approved deployment state. Automation updates only image fields.
replicaCount: 2

image:
  repository: 974462541332.dkr.ecr.us-east-1.amazonaws.com/platform-reference-service
  tag: ""
  digest: "sha256:bebf5e5067c0c4c54588b8a5ec1b62448e26f5d63a9f03da3dfcf1a18b980e5a"
  pullPolicy: IfNotPresent

configuration:
  serviceName: platform-reference-service
  serviceVersion: "0.1.0"
  gitSha: 14e18b6c0b22af2f48507ad5902806b4abcb399d
  environment: development
  logLevel: INFO

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

prometheusRule:
  enabled: true
  labels:
    release: kube-prometheus-stack
